### PR TITLE
Add webhook support

### PR DESCRIPTION
**Pull request by mpyw**

### CODE REVIEW

**Comment by sololance** [comment]
Hi!

While we're here, can we add post as json too?

Because new twitter events accepts post only as json .

Check here: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event.html

Something like this maybe? https://github.com/NKudryavka/cowitter/commit/081cdc97a87d5ad6014acabb455b7a6145b62ac9


Thank you.

**Comment by sololance** [comment]
@mpyw any update?

Thank you!

**Comment by mpyw** [comment]
@sololance Sorry, I don't feel like keep maintaining this project nowadays. Twitter has already started locking out 3rd party developers by strictly limiting API. Also I'm busy for my work at office. It's very hard for me keeping motivation.

Would you take over this project? I'll assign you as a collaborator

**Comment by sololance** [comment]
@mpyw sure, no problem I will maintain this repo because it's used in last project. Thank you ;)

**Comment by sololance** [comment]
Closed in favor of #19

**Pull request closed without merging**
